version: 0.2

env:
  variables:
    TF_VERSION: "1.7.5"
    TF_PATH: "/usr/local/bin"

phases:
  install:
    commands:
      - echo Installing Terraform CLI version $TF_VERSION
      - curl -sS -o terraform.zip https://releases.hashicorp.com/terraform/$TF_VERSION/terraform_${TF_VERSION}_linux_amd64.zip
      - unzip -o terraform.zip -d $TF_PATH
      - rm terraform.zip
      - chmod +x $TF_PATH/terraform
      - terraform version
      - aws --version

  pre_build:
    commands:
      - echo Setting up Terraform state directory
      - mkdir -p tfstate
      - terraform init

  build:
    commands:
      - echo Validating Terraform configuration
      - terraform validate
      - terraform plan -out=tfplan.out
      - terraform apply -auto-approve tfplan.out
      - cp terraform.tfstate tfstate/

  post_build:
    commands:
      - echo Terraform deployment complete
      - terraform output -raw eks_cluster_name_output || echo eks_cluster_name_output not found
      - terraform output -raw db_endpoint_address || echo db_endpoint_address not found

artifacts:
  files:
    - tfstate/terraform.tfstate
    - buildspec-deploy.yml
  discard-paths: yes
